config/routes.rb
Rails.application.routes.draw do

  resources :registres
  devise_for :users
  # Page d'accueil de l'app
  root 'pages#index'
end

app/models/registre.rb
class Registre < ActiveRecord::Base
  belongs_to :user
  belongs_to :trajet
end

app/models/trajet.rb
class Trajet < ActiveRecord::Base
  has_many :registres
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :registres, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registres_controller.rb
class RegistresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_registre, only: [:show, :edit, :update, :destroy]

  # GET /registres
  # GET /registres.json
  def index
    @registres = Registre.all
    # @total = @registres.sum(:distance)
    @total = 0
    @registres.each do |reg|
      if (reg.date.mon == Time.now.mon)
            @total = @total + reg.distance
          end
    end
  end

  # GET /registres/1
  # GET /registres/1.json
  def show
  end

  # GET /registres/new
  def new
    @registre = Registre.new
  end

  # GET /registres/1/edit
  def edit
  end

  # POST /registres
  # POST /registres.json
  def create
    @registre = Registre.new(registre_params)
    @registre.user_id = current_user.id

    respond_to do |format|
      if @registre.save
        format.html { redirect_to @registre, notice: 'La note est crée avec succes.' }
        format.json { render :show, status: :created, location: @registre }
      else
        format.html { render :new }
        format.json { render json: @registre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registres/1
  # PATCH/PUT /registres/1.json
  def update
    respond_to do |format|
      if @registre.update(registre_params)
        format.html { redirect_to @registre, notice: 'La note est mise à jour avec succès.' }
        format.json { render :show, status: :ok, location: @registre }
      else
        format.html { render :edit }
        format.json { render json: @registre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registres/1
  # DELETE /registres/1.json
  def destroy
    @registre.destroy
    respond_to do |format|
      format.html { redirect_to registres_url, notice: 'La note est supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registre
      @registre = Registre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registre_params
      params.require(:registre).permit(:motif, :date, :origine, :destination, :distance, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
 { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
end

def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
              concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                       concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                       concat content_tag(:span, 'Close', class: 'sr-only')
                     end)
              concat message
       end)
     end
    nil
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registres_helper.rb
module RegistresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MesFrais</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- Add helper for display messages -->
    <div class="message"> <%= flash_messages %></div>

    <%= render 'layouts/partials/header' %>

    <div class="container">

      <%= yield %>

    </div>

</body>
</html>

app/views/layouts/partials/_header.html.erb
<!-- Add navbar -->
<header class="navbar navbar-default" role="navigation">
   <div class="navbar-inner">
     <div class="container">
       <div id="logo" class="navbar-brand">
         <%= link_to "Mes Frais", root_path %>
       </div>
       <nav class="collapse navbar-collapse navbar-ex1-collapse">
         <% if user_signed_in? %>
           <ul class="nav navbar-nav navbar-right">
             <li>
               <%= link_to "Nouvelle note de frais", new_registre_path %>
             </li>
             <li>
               <%= link_to "Compte",  edit_user_registration_path %>
             </li>
             <li>
               <%= link_to "Deconnexion",  destroy_user_session_path, :method => :delete %>
             </li>
           </ul>
           <% else %>
             <ul class="nav navbar-nav pull-right">
               <li>
                 <%= link_to "S'inscrire",  new_user_registration_path %>
               </li>
               <li>
                 <%= link_to "Connexion",  new_user_session_path %>
               </li>
             </ul>
             <% end %>
       </nav>
     </div>
   </div>
 </header>

app/views/pages/index.html.erb
<div class="jumbotron">
    <h1>Mes frais kilométriques</h1><br>
    <p>Votre nouvelle solution de saisie pour tous vos déplacements professionnels.</p>

    <p> <%= link_to "Accéder à mon espace", registres_path, class: 'btn btn-info' %></p>
</div>

app/views/registres/_form.html.erb
<%= form_for(@registre) do |f| %>
  <% if @registre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registre.errors.count, "error") %> ont empéché l'enregistrement de cette note de frais:</h2>

      <ul>
      <% @registre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'Motif du déplacement' %><br>
    <%= f.text_field :motif %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div >
    <%= f.label :Trajet %><br>
    <!-- Add entry form to select trajet_id -->
    <%= f.collection_select(:trajet_id, Trajet.all, :id, :name, { prompt: "Selectionnez votre trajet:"} ) %>
  </div>
  <div class="field">
    <%= f.label :'Lieu de départ' %><br>
    <%= f.text_field :origine %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :'Nombre de kilomètres' %><br>
    <%= f.number_field :distance %>
  </div><br>
  <div class="actions">
    <%= f.submit 'Enregistrer'%>
  </div><br>
<% end %>

app/views/registres/edit.html.erb
<h1>Edition des notes de frais</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @registre %> |
<%= link_to 'Retour', registres_path %>

app/views/registres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing des notes de frais</h1>

<table class="table table-hover table-bordered table-responsive" >
  <thead>
    <tr>
      <th>Motif</th>
      <th>Date</th>
      <th>Lieu de départ</th>
      <th>Destination</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registres.each do |registre| %>
      <tr>
        <td><%= registre.motif %></td>
        <td><%= registre.date %></td>
        <td class=""><%= registre.origine %></td>
        <td><%= registre.destination %></td>
        <td><%= registre.distance %></td>
        <td><%= link_to 'Afficher', registre, class: 'btn btn-warning'  %></td>
        <td><%= link_to 'Editer', edit_registre_path(registre), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', registre, method: :delete, data: { confirm: 'Etes-vous sur?' }, class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="4">Total :</td>
      <td><%= @total %> </td>
      <td colspan="3"></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle note de frais', new_registre_path, class: 'btn btn-success' %>

app/views/registres/new.html.erb
<h1>Nouvelle note de frais</h1>

<%= render 'form' %>

<%= link_to 'Retour', registres_path, class: 'btn btn-warning' %>

app/views/registres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Motif du deplacement:</strong>
  <%= @registre.motif %>
</p>

<p>
  <strong>Date:</strong>
  <%= @registre.date %>
</p>

<p>
  <strong>Origine:</strong>
  <%= @registre.origine %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @registre.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @registre.distance %>
</p>


<%= link_to 'Editer', edit_registre_path(@registre), class: 'btn btn-warning' %> |
<%= link_to 'Retour', registres_path, class: 'btn btn-warning' %>